name: mlops

dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - libffi=3.3
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.8.12
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11

